name: task_manager_app
description: A Flutter app for managing tasks using Spring Boot backend.

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  fluttertoast: ^8.2.6
  url_launcher: ^6.1.10
  http: ^1.2.2
  provider: ^6.0.5
  shared_preferences: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
